### ISSUE TITLE
Failed to parse geometry attributes w/ namespace in their names 

### ISSUE THREAD

**Issue by msekoranja** [exxamalte/python-georss-client#24]
I have been trying to parse

https://www.emsc-csem.org/service/rss/rss.php?typ=emsc&min_lat=10&min_long=-30&max_long=65

with generic georss client. I always get 0 entries.

I debugged it a bit:
```
>>> print(feed._fetch()[1].entries[0]._source)
OrderedDict([('title', 'ML 2.1  CROATIA'), ('link', 'https://www.emsc-csem.org/Earthquake/earthquake.php?id=933959'), ('http://www.w3.org/2003/01/geo/:lat', '45.43'), ('http://www.w3.org/2003/01/geo/:long', '16.05'), ('https://www.emsc-csem.org:depth', '1'), ('https://www.emsc-csem.org:magnitude', 'ML 2.1'), ('https://www.emsc-csem.org:time', '2020-12-29 22:45:32 UTC'), ('pubDate', datetime.datetime(2020, 12, 29, 22, 53, tzinfo=<StaticTzInfo 'UTC\+00:00'>)), ('status', 'AUTOMATIC'), ('guid', 'https://www.emsc-csem.org/Earthquake/earthquake.php?id=933959'), ('comments', '2020-12-29 22:45:32 UTC'), ('description', '<table><tr><td><table cellpadding="0" cellspacing="0" border="0" style="margin-top:5px; font-size:11px;"><tr><td style="padding-right:4px">Magnitude</td><td class="point2">&nbsp;&nbsp;ML 2.1</td></tr><tr><td style="padding-right:4px">Region</td><td class="point2">&nbsp;&nbsp;CROATIA</td></tr><tr><td style="padding-right:4px">Date time</td><td class="point2">&nbsp;&nbsp;2020-12-29   22:45:32.0 UTC</td></tr><tr><td style="padding-right:4px">Location</td><td class="point2">&nbsp;&nbsp;45.43 N ; 16.05 E</td></tr><tr><td style="padding-right:4px">Depth</td><td class="point2">&nbsp;&nbsp;1 km</td></tr></table></td></tr></table>')])
```

... and it looks like that the parser sets full attribute name (i.e. including namespace).
Later on feed_item.py simple checkes for:
```python
        # <geo:long>119.948006</geo:long>
        # <geo:lat>-23.126413</geo:lat>
        lat = self._attribute([XML_TAG_GEO_LAT])
        long = self._attribute([XML_TAG_GEO_LONG])
```

where 

```python
XML_TAG_GEO_LAT = 'geo:lat'
XML_TAG_GEO_LONG = 'geo:long'
```

and it does not find geometry.

BTW Is there a EMSC GeoRSS client implemented (instead of generic)? Earthquakes are nearby (100km, Croatia) and I want to get info in my Home assistant.

**Comment by exxamalte** [comment]
Thanks for your analysis. It appears that this particular feed uses a namespace that I wasn't expecting: The standard namespace is `xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#"` while this feed for some reason defines `xmlns:geo="http://www.w3.org/2003/01/geo/"`.

Let me see if I can fix this by simply adding this alternative URL.

> BTW Is there a EMSC GeoRSS client implemented (instead of generic)? Earthquakes are nearby (100km, Croatia) and I want to get info in my Home assistant.

There is currently no EMSC specific implementation. I have implemented various other integration libraries, and I have also ported some of the libraries to async versions with https://github.com/exxamalte/python-aio-georss-client as a base implementation.
Are you a software developer and would be interested in creating an EMSC specific version of this library yourself? I'm happy to help.

**Comment by msekoranja** [comment]
Thanks. Now it works.

I am a software developer, but I have not do anything serious in Python (I am more Java, C, C++ developer).
Anyway, I have created the following project (non-aio for a start) and it works nicely via command-line:
https://github.com/msekoranja/python-georss-emsc-csem-earthquakes-client

The idea is to integrate this in HA, filtering by radius and magnitude and show title, time, magnitude and link for matched earthquakes.

**Comment by exxamalte** [comment]
That looks like a great start. Let me know if you need any help.
