### ISSUE TITLE
Pinned requests requirement

### ISSUE THREAD

**Issue by MartinHjelmare** [exxamalte/python-georss-client#7]
Hi! Please loosen the version requirement of requests. If possible just require requests, but a minimum version is ok too.

Pinning requirements in libraries complicates things for apps, like home assistant, that use this library, eg if the apps need a higher version.

https://github.com/exxamalte/python-georss-client/blob/master/setup.py#L10

**Comment by exxamalte** [comment]
Good point. Let me take a quick look at what minimum requirements this library actually has.
